### ISSUE TITLE
[Data Replicator] Automatizar criação da tabela destino clonada da tabela origem

### ISSUE THREAD

**Issue by nitaibezerra** [gestaogovbr/FastETL#42]
Evoluir os plugins de replicação de tabelsa _full_ e completa para automaticamente criarem (caso não exista) a tabela no banco de dados destino a partir da estrutura da tabela do banco de dados origem. Isso reduzirá a barreira para utilização dos plugins.

**Comment by edulauer** [comment]
#168

**Comment by edulauer** [comment]
Implementado.
